service: mottu-zendesk-files
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  zendesk-upload-file:
    handler: index.uploadFileToZendesk
    events:
      - httpApi:
          path: /
          method: post
    environment:
      ZENDESK_TOKEN: ${env:ZENDESK_TOKEN}
      ZENDESK_SUBDOMAIN: ${env:ZENDESK_SUBDOMAIN}
      ZENDESK_API_VERSION: ${env:ZENDESK_API_VERSION}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

useDotenv: true